# データ設定
data_dirs:
  chat_messages: "../data/chat_messages"
  transcription_source: "../data/transcription/source"
  transcription_clipping: "../data/transcription/clipping"
  comparison_matches: "../data/comparison/matches"
  emotion: "../data/emotion"
similarity_threshold: 0.75

train_files: "../data/train_data.csv"
test_files: "../data/test_data.csv"


# モデル設定
model:
  vocab_size: 30522          # ボキャブラリのサイズ（例: BERTのトークナイザー用）
  embedding_dim: 128         # 埋め込み次元
  hidden_dim: 256            # 隠れ層の次元
  output_dim: 2              # 出力次元（例: クラス数）

# 学習設定
training:
  batch_size: 32             # バッチサイズ
  num_epochs: 10             # エポック数
  learning_rate: 0.001       # 学習率
  seed: 42                   # 再現性のためのランダムシード

# 評価設定
evaluation:
  batch_size: 32             # 評価時のバッチサイズ

# その他
logging:
  level: "INFO"              # ログの出力レベル
  save_interval: 1           # モデルを保存する間隔（エポック単位）
